version: "3"

services:

  ha-proxy:
    image: quay.io/prometheus/haproxy-exporter:${HA_PROXY_TAG:-latest}
    networks:
      - proxy
      - monitor
    deploy:
      labels:
        - com.df.notify=true
        - com.df.scrapePort=9101
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 50M
    command: --haproxy.scrape-uri="http://admin:admin@proxy/admin?stats;csv"

  cadvisor:
    image: google/cadvisor:${CADVISOR_TAG:-latest}
    networks:
      - monitor
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.scrapePort=8080
      resources:
        reservations:
          memory: 30M
        limits:
          memory: 50M

  node-exporter-manager:
    image: basi/node-exporter:${NODE_EXPORTER_TAG:-v1.14.0}
    networks:
      - monitor
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
      - LOGSPOUT=ignore
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.scrapePort=9100
        - com.df.alertName.1=mem_limit
        - com.df.alertIf.1=@node_mem_limit:0.8
        - com.df.alertFor.1=30s
        - com.df.alertName.2=node_mem_limit_total_above
        - com.df.alertIf.2=@node_mem_limit_total_above:0.8
        - com.df.alertLabels.2=receiver=system,scale=no,service=exporter_node-exporter-manager,type=node
        - com.df.alertFor.2=30s
        - com.df.alertName.3=service_mem_limit
        - com.df.alertIf.3=@service_mem_limit:0.8
        - com.df.alertFor.3=30s
      placement:
        constraints:
          - node.role == manager
      resources:
        reservations:
          memory: 30M
        limits:
          memory: 50M
    command: '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" -collector.textfile.directory /etc/node-exporter/ -collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"'

  node-exporter-worker:
    image: basi/node-exporter:${NODE_EXPORTER_TAG:-v1.14.0}
    networks:
      - monitor
    environment:
      - HOST_HOSTNAME=/etc/host_hostname
      - LOGSPOUT=ignore
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
      - /etc/hostname:/etc/host_hostname
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.scrapePort=9100
        - com.df.alertName.1=mem_limit
        - com.df.alertIf.1=@node_mem_limit:0.8
        - com.df.alertFor.1=30s
        - com.df.alertName.2=node_mem_limit_total_above
        - com.df.alertIf.2=@node_mem_limit_total_above:0.8
        - com.df.alertFor.2=30s
        - com.df.alertName.3=node_mem_limit_total_below
        - com.df.alertIf.3=@node_mem_limit_total_below:0.05 # For testing purposes only. A better value would be `0.4`.
        - com.df.alertFor.3=30s
        - com.df.alertName.4=service_mem_limit
        - com.df.alertIf.4=@service_mem_limit:0.8
        - com.df.alertFor.4=30s
      placement:
        constraints:
          - node.role == worker
      resources:
        reservations:
          memory: 30M
        limits:
          memory: 50M
    command: '-collector.procfs /host/proc -collector.sysfs /host/sys -collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)" -collector.textfile.directory /etc/node-exporter/ -collectors.enabled="conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,stat,textfile,time,vmstat,ipvs"'

networks:
  monitor:
    external: true
  proxy:
    external: true