version: "3.1"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - xpack.security.enabled=false
    volumes:
      - es:/usr/share/elasticsearch/data
    networks:
      - default
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 1500M
        limits:
          memory: 1900M
      placement:
        constraints: [node.role == worker]

  logstash:
    image: vfarcic/logstash:5.5.2
    networks:
      - default
    deploy:
      labels:
        - com.df.distribute=true
        - com.df.notify=true
        - com.df.port=80
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 600M
        limits:
          memory: 1000M
    environment:
      - LOGSPOUT=ignore

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.2
    networks:
      - default
      - proxy
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_BASEPATH=/kibana
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.usersPassEncrypted=false
        - com.df.usersSecret=vfarcic
        - com.df.servicePath=/kibana
        - com.df.port=5601
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 150M
        limits:
          memory: 300M

  logspout:
    image: gliderlabs/logspout:v3.2.2
    networks:
      - default
    environment:
      - SYSLOG_FORMAT=rfc3164
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: syslog://logstash:51415
    deploy:
      mode: global
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.alertName=memlimit
        - com.df.alertIf=@service_mem_limit:0.8
        - com.df.alertFor=30s
      resources:
        reservations:
          memory: 20M
        limits:
          memory: 30M

networks:
  proxy:
    external: true
  default:
    external: false

volumes:
  es:
    driver: cloudstor:aws
    external: false
